### ISSUE TITLE
Error(11): Error, Create link exception!!

### ISSUE THREAD

**Issue by jflot** [rkajitani/Platanus_B#3]
Hello,
I am trying Platanus_B on a bacterial dataset. The first step (assemble) worked well but the second step (iterate) failed with the error message "Error(11): Error, Create link exception!!
ln, cp, mv or cat command failed."

$platanus_b assemble -f Illumina_reads1_trimmed.fq Illumina_reads2_trimmed.fq -t 50

platanus_b version: 1.3.2
platanus_b assemble -f Illumina_reads1_trimmed.fq Illumina_reads2_trimmed.fq -t 50 

K = 32, saving kmers from reads...
AVE_READ_LEN=149.906

KMER_EXTENSION:
K=32, KMER_COVERAGE=68.1114 (>= 9), COVERAGE_CUTOFF=9
K=42, KMER_COVERAGE=62.3832, COVERAGE_CUTOFF=9, PROB_SPLIT=10e-15.9546
K=52, KMER_COVERAGE=56.6551, COVERAGE_CUTOFF=9, PROB_SPLIT=10e-14.0795
K=62, KMER_COVERAGE=50.9269, COVERAGE_CUTOFF=9, PROB_SPLIT=10e-11.9534
K=72, KMER_COVERAGE=45.1988, COVERAGE_CUTOFF=8, PROB_SPLIT=10e-10.6336
K=82, KMER_COVERAGE=39.4706, COVERAGE_CUTOFF=6, PROB_SPLIT=10e-10.1412
K=92, KMER_COVERAGE=33.7424, COVERAGE_CUTOFF=3, PROB_SPLIT=10e-10.8317
K=102, KMER_COVERAGE=28.0143, COVERAGE_CUTOFF=1, PROB_SPLIT=10e-11.1251
K=107, KMER_COVERAGE=25.1502, COVERAGE_CUTOFF=1, PROB_SPLIT=10e-10.1444
K=108, KMER_COVERAGE=24.5774, COVERAGE_CUTOFF=1, PROB_SPLIT=10e-10.3728
K=109, KMER_COVERAGE=24.0046, COVERAGE_CUTOFF=1, PROB_SPLIT=10e-10.124
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=1328
NUM_CUT=3
NUM_CUT=0
TOTAL_NUM_CUT=1331
extracting reads (containing kmer used in contig assemble)...
K = 42, loading kmers from contigs...
K = 42, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 9
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=278
NUM_CUT=1
NUM_CUT=0
TOTAL_NUM_CUT=279
extracting reads (containing kmer used in contig assemble)...
K = 52, loading kmers from contigs...
K = 52, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 9
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=183
NUM_CUT=2
NUM_CUT=0
TOTAL_NUM_CUT=185
extracting reads (containing kmer used in contig assemble)...
K = 62, loading kmers from contigs...
K = 62, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 9
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=127
NUM_CUT=1
NUM_CUT=0
TOTAL_NUM_CUT=128
extracting reads (containing kmer used in contig assemble)...
K = 72, loading kmers from contigs...
K = 72, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 8
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=112
NUM_CUT=0
TOTAL_NUM_CUT=112
extracting reads (containing kmer used in contig assemble)...
K = 82, loading kmers from contigs...
K = 82, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 6
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=161
NUM_CUT=1
NUM_CUT=0
TOTAL_NUM_CUT=162
extracting reads (containing kmer used in contig assemble)...
K = 92, loading kmers from contigs...
K = 92, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 3
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=489
NUM_CUT=5
NUM_CUT=0
TOTAL_NUM_CUT=494
extracting reads (containing kmer used in contig assemble)...
K = 102, loading kmers from contigs...
K = 102, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 1
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=6321
NUM_CUT=51
NUM_CUT=0
TOTAL_NUM_CUT=6372
extracting reads (containing kmer used in contig assemble)...
K = 107, loading kmers from contigs...
K = 107, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 1
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=4417
NUM_CUT=41
NUM_CUT=0
TOTAL_NUM_CUT=4458
extracting reads (containing kmer used in contig assemble)...
K = 108, loading kmers from contigs...
K = 108, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 1
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=3227
NUM_CUT=25
NUM_CUT=0
TOTAL_NUM_CUT=3252
extracting reads (containing kmer used in contig assemble)...
K = 109, loading kmers from contigs...
K = 109, saving additional kmers(not found in contigs) from reads...
COVERAGE_CUTOFF = 1
loading kmers...
connecting kmers...
removing branches...
BRANCH_DELETE_THRESHOLD=0.5
NUM_CUT=3078
NUM_CUT=25
NUM_CUT=0
TOTAL_NUM_CUT=3103
LENGTH_CUTOFF = 218
COVERAGE_CUTOFF = 3
removing erroneous nodes...
NUM_REMOVED_NODES=3124
NUM_REMOVED_NODES=534
NUM_REMOVED_NODES=6
NUM_REMOVED_NODES=0
TOTAL_NUM_REMOVED_NODES=3664
extracting reads (containing kmer used in contig assemble)...
K = 109, loading kmers from contigs...
K = 109, saving additional kmers(not found in contigs) from reads...
loading kmers...
connecting kmers...
assemble completed!

$platanus_b iterate -c out_contig.fa -IP1 Illumina_reads1-trimmed.fq Illumina_reads2-trimmed.fastq -ont ONT_reads.fa -t 50 

checking sub-executables ...
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/close_gap.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/combinatorial_gap_close.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/fasta_around_gap.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/fasta_grep.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/get_flanked_region_info_outer.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/get_flanked_region_info.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/paf_contained_short_seq_list_bubble_aware.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/paf_filter_flanking_pair.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/paf_filter_qcov.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/paf_match_short_seq_list_bubble_aware.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/paf_max_match_unique.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/reduce_filled_info.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/remove_redundant_seq.pl
/opt/binf-f-402/part2/src/Platanus_B/sub_bin/minimap2
all sub-executables found

Error(11): Error, Create link exception!!
ln, cp, mv or cat command failed.

Thanks a lot in advance for your help.

**Comment by rkajitani** [comment]
Sorry for the late reply, and your command looks correct.
Could you please paste the output of the command below?
`ls -l out_iterateIntermediateResults/*`

**Comment by jflot** [comment]
Here is the output:
`-rw-r--r-- 1 jflot padi-linux-users 275 Dec 10 16:36 out_iterateIntermediateResults/out.countKmerLog`

Here is the content of the file:
`cat out_iterateIntermediateResults/out.countKmerLog 
platanus_b version: 1.3.2
platanus_b assemble -kmer_occ_only -n 1 -t 50 -m 1 -tmp . -k 109 -o out_iterateIntermediateResults/out -f Illumina_reads1-trimmed.fq Illumina_reads2-trimmed.fastq 
Error(1): Error, File not open exception!!
Illumina_reads1-trimmed.fq is not open!!`

This allowed me to identify the problem: the input files were actually named Illumina_reads1_trimmed.fq  and Illumina_reads1_trimmed.fq, not Illumina_reads1-trimmed.fq  and Illumina_reads2-trimmed.fq  as I had mistakenly written in my second command...

Thanks again for your help!

**Comment by rkajitani** [comment]
I see. Thank you for the report!
